name: Sample Book App

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Print output
        run: echo Building of node application is starting..        
  deploy-dev:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Print output
        run: echo Deployment to DEV has started..
  test-dev:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Print output
        run: echo Testing BOOKS test set on DEV has started..
  deploy-stg:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Print output
        run: echo Deployment to STG has started..
  test-stg:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Print output
        run: echo Testing BOOKS test set on STG has started..
  deploy-prd:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Print output
        run: echo Deployment to PRD has started..
  test-prd:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Print output
        run: echo Testing BOOKS test set on PRD has started..




